// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'extract-error'
  | 'extract-progress'
  | 'extract-progress-complete'
  | 'extract-progress-current'
  | 'extract-progress-processing'
  | 'extract-success'
  | 'menuitem-extract-label'
  | 'pref-about-feedback'
  | 'pref-about-title'
  | 'pref-about-version'
  | 'pref-add-better-rss-tag-label'
  | 'pref-add-feed-name-tag-label'
  | 'pref-auto-extract-label'
  | 'pref-auto-extraction-title'
  | 'pref-content-saving-title'
  | 'pref-folder-path-template-hint'
  | 'pref-folder-path-template-label'
  | 'pref-save-note-label'
  | 'pref-save-snapshot-label'
  | 'pref-save-to-folder-label'
  | 'pref-tagging-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
